import { getCollection } from "astro:content";
import { getCategoryList, recipeHref, visibleRecipes } from "@/lib/recipes";
import { absoluteUrl } from "@/lib/url";
import { escapeXml } from "@/lib/xml";
import { sitemapStaticRoutes } from "@/lib/routes";

type Entry = { href: string; lastmod?: Date };

/**
 * Only recipes declare a date, so static pages carry no `<lastmod>`. Stamping
 * them with the build clock instead would make every unchanged page look
 * freshly edited on each deploy.
 */
const toUrlEntry = ({ href, lastmod }: Entry) => {
  const url = absoluteUrl(href);
  // Sitemap dates must be W3C Datetime.
  const modified = lastmod ? `\n    <lastmod>${lastmod.toISOString()}</lastmod>` : "";
  return `  <url>\n    <loc>${escapeXml(url)}</loc>${modified}\n  </url>`;
};

/**
 * Hand-written rather than generated by `@astrojs/sitemap` because that
 * integration only ever writes `sitemap-0.xml` + `sitemap-index.xml` — the
 * filenames are hardcoded, with no option to serve `/sitemap.xml`.
 *
 * Static routes come from `sitemapStaticRoutes` in `@/lib/routes`, so a new
 * page only needs adding there. Only non-`noindex` pages belong there:
 * `/pesquisar/` (search), `/401/`, `/404/` and print sheets are internal
 * and are deliberately absent.
 */
export async function GET() {
  const recipes = await getCollection("recipes");

  const entries: Entry[] = [
    ...sitemapStaticRoutes.map((href) => ({ href })),
    ...getCategoryList(recipes).map(({ slug }) => ({ href: `/categorias/${slug}/` })),
    ...visibleRecipes(recipes).map((recipe) => ({
      href: recipeHref(recipe),
      lastmod: recipe.data.date,
    })),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.map(toUrlEntry).join("\n")}
</urlset>
`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
    },
  });
}
